using System.Collections.Immutable;
using Humans.Analyzers.Internal;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Humans.Analyzers;

/// <summary>
/// HUM0009 — Only repository classes (transitive implementers of
/// <c>Humans.Application.Interfaces.Repositories.IRepository</c>) may use
/// <c>HumansDbContext</c>. Every other class must go through a repository or
/// service. Existing pre-rule violators may carry
/// <c>[Grandfathered("HUM0009", …)]</c> — the analyzer downgrades the
/// diagnostic to <c>Warning</c> for those, but new violators (no attribute)
/// fire <c>Error</c>.
/// </summary>
/// <remarks>
/// Runs in <c>Humans.Infrastructure</c> only. That's the only compilation
/// where both <c>HumansDbContext</c> and every candidate user type are
/// declared: Application has no project reference to Infrastructure so
/// <c>HumansDbContext</c> is unresolvable there, and Web's analysis only sees
/// types declared in Web (controllers).
/// </remarks>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class ApplicationServiceDbContextInjectionAnalyzer : DiagnosticAnalyzer
{
    public const string DiagnosticId = "HUM0009";

    private static readonly LocalizableString Title =
        "Non-repository class uses HumansDbContext";

    private static readonly LocalizableString MessageFormat =
        "'{0}' uses HumansDbContext but does not implement IRepository. Route the DB access through a repository or service.";

    public static readonly DiagnosticDescriptor Rule = new(
        id: DiagnosticId,
        title: Title,
        messageFormat: MessageFormat,
        category: AnalyzerCategories.Architecture,
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description:
            "HumansDbContext is the persistence boundary; only repositories may touch it. " +
            "Classes outside the repository layer that need persisted state must call a service " +
            "or repository. Existing violators may carry [Grandfathered(\"HUM0009\", …)] which " +
            "downgrades this diagnostic to a warning for the tagged class only — the attribute " +
            "is a TODO for migration, not a permanent exemption.");

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        ImmutableArray.Create(Rule);

    private const string HumansDbContextFullName = "Humans.Infrastructure.Data.HumansDbContext";
    private const string IRepositoryFullName = "Humans.Application.Interfaces.Repositories.IRepository";
    private const string GrandfatheredAttributeFullName = "Humans.Application.Architecture.GrandfatheredAttribute";

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        context.RegisterCompilationStartAction(OnCompilationStart);
    }

    private static void OnCompilationStart(CompilationStartAnalysisContext context)
    {
        if (!string.Equals(context.Compilation.Assembly.Name, AssemblyScope.Infrastructure, System.StringComparison.Ordinal))
            return;

        var dbContextType = context.Compilation.GetTypeByMetadataName(HumansDbContextFullName);
        if (dbContextType is null)
            return;

        var repositoryMarker = context.Compilation.GetTypeByMetadataName(IRepositoryFullName);
        if (repositoryMarker is null)
            return;

        var grandfatheredAttr = context.Compilation.GetTypeByMetadataName(GrandfatheredAttributeFullName);

        context.RegisterSymbolAction(
            ctx => AnalyzeNamedType(ctx, dbContextType, repositoryMarker, grandfatheredAttr),
            SymbolKind.NamedType);
    }

    private static void AnalyzeNamedType(
        SymbolAnalysisContext context,
        INamedTypeSymbol dbContextType,
        INamedTypeSymbol repositoryMarker,
        INamedTypeSymbol? grandfatheredAttr)
    {
        var type = (INamedTypeSymbol)context.Symbol;
        if (type.TypeKind != TypeKind.Class)
            return;

        // Don't flag HumansDbContext itself, EF migration files, or types
        // generated by the EF designer.
        if (SymbolEqualityComparer.Default.Equals(type, dbContextType))
            return;

        // Allow repository implementations — the rule's whole point is "use
        // a repository instead."
        if (ImplementsRepositoryMarker(type, repositoryMarker))
            return;

        var location = FindFirstDbContextReference(type, dbContextType);
        if (location is null)
            return;

        var severity = HasGrandfatherForHum0009(type, grandfatheredAttr)
            ? DiagnosticSeverity.Warning
            : DiagnosticSeverity.Error;

        context.ReportDiagnostic(Diagnostic.Create(
            descriptor: Rule,
            location: location,
            effectiveSeverity: severity,
            additionalLocations: null,
            properties: null,
            messageArgs: type.Name));
    }

    private static bool ImplementsRepositoryMarker(INamedTypeSymbol type, INamedTypeSymbol repositoryMarker)
    {
        foreach (var iface in type.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(iface, repositoryMarker))
                return true;
        }
        return false;
    }

    /// <summary>
    /// Finds the first structural reference to HumansDbContext on the type —
    /// base type, implemented interface, field, property, or method
    /// (parameter or return type). Recurses through generic type arguments
    /// so <c>UserStore&lt;…, HumansDbContext, …&gt;</c> also matches.
    /// Returns null if the type does not use HumansDbContext structurally.
    /// </summary>
    private static Location? FindFirstDbContextReference(INamedTypeSymbol type, INamedTypeSymbol dbContextType)
    {
        if (type.BaseType is { } baseType && TypeReferences(baseType, dbContextType))
            return PreferFirstSyntax(type);

        foreach (var iface in type.Interfaces)
        {
            if (TypeReferences(iface, dbContextType))
                return PreferFirstSyntax(type);
        }

        foreach (var member in type.GetMembers())
        {
            switch (member)
            {
                case IFieldSymbol field when TypeReferences(field.Type, dbContextType):
                    return PreferFirst(field.Locations);

                case IPropertySymbol prop when TypeReferences(prop.Type, dbContextType):
                    return PreferFirst(prop.Locations);

                case IMethodSymbol method:
                    if (TypeReferences(method.ReturnType, dbContextType))
                        return PreferFirst(method.Locations);

                    foreach (var parameter in method.Parameters)
                    {
                        if (TypeReferences(parameter.Type, dbContextType))
                            return PreferFirst(parameter.Locations);
                    }
                    break;
            }
        }

        return null;
    }

    /// <summary>
    /// Recursively walks a type and its generic arguments, looking for
    /// HumansDbContext. Handles arrays, nullable, and arbitrarily-nested
    /// generic constructions.
    /// </summary>
    private static bool TypeReferences(ITypeSymbol? candidate, INamedTypeSymbol dbContextType)
    {
        if (candidate is null)
            return false;

        if (SymbolEqualityComparer.Default.Equals(candidate, dbContextType))
            return true;

        if (candidate is INamedTypeSymbol named)
        {
            foreach (var typeArg in named.TypeArguments)
            {
                if (TypeReferences(typeArg, dbContextType))
                    return true;
            }
        }

        if (candidate is IArrayTypeSymbol arr && TypeReferences(arr.ElementType, dbContextType))
            return true;

        return false;
    }

    private static Location? PreferFirstSyntax(INamedTypeSymbol type) =>
        type.Locations.Length > 0 ? type.Locations[0] : null;

    private static Location? PreferFirst(ImmutableArray<Location> locations) =>
        locations.Length > 0 ? locations[0] : null;

    private static bool HasGrandfatherForHum0009(INamedTypeSymbol type, INamedTypeSymbol? grandfatheredAttr)
    {
        if (grandfatheredAttr is null)
            return false;

        foreach (var attr in type.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attr.AttributeClass, grandfatheredAttr))
                continue;

            if (attr.ConstructorArguments.Length == 0)
                continue;

            var ruleIdArg = attr.ConstructorArguments[0];
            if (ruleIdArg.Value is string ruleId &&
                string.Equals(ruleId, DiagnosticId, System.StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }
}
