using System.Globalization;
using Humans.Application.DTOs;
using Humans.Application.Extensions;
using Humans.Application.Interfaces.Budget;
using Humans.Application.Interfaces.Gdpr;
using Humans.Application.Interfaces.Repositories;
using Humans.Application.Interfaces.Teams;
using Humans.Application.Interfaces.Users;
using Humans.Domain.Entities;
using Humans.Domain.Enums;
using Microsoft.Extensions.Logging;
using NodaTime;

namespace Humans.Application.Services.Budget;

/// <summary>
/// Budget service. Cross-section reads (teams) via ITeamService. budget_audit_logs is append-only (§12).
/// </summary>
public sealed class BudgetService(
    IBudgetRepository repository,
    ITeamService teamService,
    IUserServiceRead userService,
    IClock clock,
    ILogger<BudgetService> logger) : IBudgetService, IUserDataContributor
{
    public async Task<IReadOnlyList<BudgetYearSummarySnapshot>> GetAllYearsAsync(bool includeArchived = false)
    {
        var years = await repository.GetAllYearsAsync(includeArchived);
        return years.Select(ToYearSummarySnapshot).ToList();
    }

    private static BudgetYearSummarySnapshot ToYearSummarySnapshot(BudgetYear year) =>
        new(
            year.Id,
            year.Year,
            year.Name,
            year.Status,
            year.IsDeleted,
            year.Groups
                .Select(group => new BudgetGroupSummarySnapshot(
                    group.Id,
                    group.Name,
                    group.SortOrder,
                    group.IsRestricted,
                    group.IsDepartmentGroup))
                .ToList());

    public async Task<BudgetYearDetail?> GetYearByIdAsync(Guid id)
    {
        var year = await repository.GetYearByIdAsync(id);
        return year is null ? null : ToYearDetail(year);
    }

    public async Task<BudgetYearDetail?> GetActiveYearAsync()
    {
        var year = await repository.GetActiveYearAsync();
        return year is null ? null : ToYearDetail(year);
    }

    private static BudgetYearDetail ToYearDetail(BudgetYear year) =>
        new(
            year.Id,
            year.Year,
            year.Name,
            year.Status,
            year.IsDeleted,
            year.Groups
                .Select(ToGroupDetail)
                .ToList());

    private static BudgetGroupDetail ToGroupDetail(BudgetGroup group) =>
        new(
            group.Id,
            group.BudgetYearId,
            group.Name,
            group.SortOrder,
            group.IsRestricted,
            group.IsDepartmentGroup,
            group.IsTicketingGroup,
            group.TicketingProjection is null
                ? null
                : new TicketingProjectionSnapshot(
                    group.TicketingProjection.Id,
                    group.TicketingProjection.BudgetGroupId,
                    group.TicketingProjection.StartDate,
                    group.TicketingProjection.EventDate,
                    group.TicketingProjection.InitialSalesCount,
                    group.TicketingProjection.DailySalesRate,
                    group.TicketingProjection.AverageTicketPrice,
                    group.TicketingProjection.VatRate,
                    group.TicketingProjection.StripeFeePercent,
                    group.TicketingProjection.StripeFeeFixed,
                    group.TicketingProjection.TicketTailorFeePercent,
                    group.TicketingProjection.CreatedAt,
                    group.TicketingProjection.UpdatedAt),
            group.Categories
                .Select(ToCategoryDetail)
                .ToList());

    private static BudgetCategoryDetail ToCategoryDetail(BudgetCategory category) =>
        new(
            category.Id,
            category.BudgetGroupId,
            category.Name,
            category.AllocatedAmount,
            category.ExpenditureType,
            category.TeamId,
            category.SortOrder,
            category.LineItems
                .Select(item => new BudgetLineItemDetail(
                    item.Id,
                    item.BudgetCategoryId,
                    item.Description,
                    item.Amount,
                    item.ResponsibleTeamId,
                    item.Notes,
                    item.ExpectedDate,
                    item.VatRate,
                    item.IsAutoGenerated,
                    item.IsCashflowOnly,
                    item.SortOrder))
                .ToList());

    public async Task<CoordinatorBudgetViewData> GetCoordinatorBudgetViewDataAsync(Guid userId, bool isFinanceAdmin)
    {
        var coordinatorTeamIds = await GetEffectiveCoordinatorTeamIdsAsync(userId);
        if (!isFinanceAdmin && coordinatorTeamIds.Count == 0)
            return new CoordinatorBudgetViewData(null, coordinatorTeamIds, isFinanceAdmin, ShouldRedirectToSummary: true);

        var activeYear = await GetActiveYearAsync();
        return new CoordinatorBudgetViewData(activeYear, coordinatorTeamIds, isFinanceAdmin, ShouldRedirectToSummary: false);
    }

    public async Task<BudgetYearDetail> CreateYearAsync(string year, string name, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        // Resolve budgetable teams via Teams service (§2c).
        var teams = (await teamService.GetTeamsAsync()).Values
            .Where(t => t.IsActive && t.HasBudget)
            .OrderBy(t => t.Name, StringComparer.Ordinal);
        var teamRefs = teams
            .Select(t => new BudgetableTeamRef(t.Id, t.Name))
            .ToList();

        var draft = new BudgetYearDraft(
            Id: Guid.NewGuid(),
            Year: year,
            Name: name,
            BudgetableTeams: teamRefs,
            ActorUserId: actorUserId,
            Now: now);

        await repository.CreateYearWithScaffoldAsync(draft);

        logger.LogInformation(
            "Created budget year {Year} ({Name}) with {TeamCount} department categories",
            year, name, teamRefs.Count);

        return new BudgetYearDetail(
            draft.Id,
            year,
            name,
            BudgetYearStatus.Draft,
            IsDeleted: false,
            Groups: []);
    }

    public async Task UpdateYearStatusAsync(Guid yearId, BudgetYearStatus status, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var ok = await repository.UpdateYearStatusAsync(yearId, status, actorUserId, now);
        if (!ok)
            throw new InvalidOperationException($"Budget year {yearId} not found");

        logger.LogInformation(
            "Updated budget year {YearId} status to {NewStatus}",
            yearId, status);
    }

    public async Task UpdateYearAsync(Guid yearId, string year, string name, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var ok = await repository.UpdateYearAsync(yearId, year, name, actorUserId, now);
        if (!ok)
            throw new InvalidOperationException($"Budget year {yearId} not found");
    }

    public async Task DeleteYearAsync(Guid yearId, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var ok = await repository.SoftDeleteYearAsync(yearId, actorUserId, now);
        if (!ok)
            throw new InvalidOperationException($"Budget year {yearId} not found");

        logger.LogInformation("Archived budget year {YearId}", yearId);
    }

    public async Task RestoreYearAsync(Guid yearId, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var restored = await repository.RestoreYearAsync(yearId, actorUserId, now);
        if (restored)
            logger.LogInformation("Restored budget year {YearId}", yearId);
    }

    public async Task<int> SyncDepartmentsAsync(Guid budgetYearId, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var teams = (await teamService.GetTeamsAsync()).Values
            .Where(t => t.IsActive && t.HasBudget)
            .OrderBy(t => t.Name, StringComparer.Ordinal);
        var teamRefs = teams
            .Select(t => new BudgetableTeamRef(t.Id, t.Name))
            .ToList();

        var created = await repository.SyncDepartmentCategoriesAsync(
            budgetYearId, teamRefs, actorUserId, now);

        if (created > 0)
            logger.LogInformation(
                "Synced {Count} departments into budget year {YearId}",
                created, budgetYearId);

        return created;
    }

    public async Task<EnsureTicketingGroupResult> EnsureTicketingGroupAsync(Guid budgetYearId, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var created = await repository.EnsureTicketingGroupAsync(budgetYearId, actorUserId, now);

        if (created)
            logger.LogInformation("Added ticketing group to budget year {YearId}", budgetYearId);

        return new EnsureTicketingGroupResult(
            created,
            created
                ? "Ticketing group added to this budget year."
                : "Ticketing group already exists for this budget year.");
    }

    public async Task<BudgetGroupDetail> CreateGroupAsync(
        Guid budgetYearId, string name, bool isRestricted, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var group = await repository.CreateGroupAsync(
            budgetYearId, name, isRestricted, actorUserId, now);

        logger.LogInformation(
            "Created budget group '{Name}' in year {YearId}", name, budgetYearId);

        return ToGroupDetail(group);
    }

    public async Task UpdateGroupAsync(
        Guid groupId, string name, int sortOrder, bool isRestricted, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var ok = await repository.UpdateGroupAsync(
            groupId, name, sortOrder, isRestricted, actorUserId, now);
        if (!ok)
            throw new InvalidOperationException($"Budget group {groupId} not found");
    }

    public async Task DeleteGroupAsync(Guid groupId, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var ok = await repository.DeleteGroupAsync(groupId, actorUserId, now);
        if (!ok)
            throw new InvalidOperationException($"Budget group {groupId} not found");

        logger.LogInformation("Deleted budget group {GroupId}", groupId);
    }

    public async Task<BudgetCategorySnapshot?> GetCategoryByIdAsync(Guid id)
    {
        var category = await repository.GetCategoryByIdAsync(id);
        if (category is null)
            return null;

        // Stitch team names via ITeamService.
        var teamIds = category.LineItems
            .Select(li => li.ResponsibleTeamId)
            .Where(tid => tid.HasValue)
            .Select(tid => tid!.Value)
            .Distinct()
            .ToList();

        var teamNamesById = new Dictionary<Guid, string>();
        if (teamIds.Count > 0)
        {
            var teams = await teamService.GetTeamsAsync();
            foreach (var teamId in teamIds)
            {
                if (teams.TryGetValue(teamId, out var team))
                    teamNamesById[teamId] = team.Name;
            }
        }

        return ToCategorySnapshot(category, teamNamesById);
    }

    public async Task<CoordinatorCategoryDetailViewData> GetCoordinatorCategoryDetailViewDataAsync(
        Guid categoryId, Guid userId, bool isFinanceAdmin)
    {
        var category = await GetCategoryByIdAsync(categoryId);
        if (category is null)
            return new CoordinatorCategoryDetailViewData(null, ShouldForbid: false, Teams: []);

        var isRestricted = category.BudgetGroup?.IsRestricted == true || category.BudgetGroup?.IsTicketingGroup == true;
        if (isRestricted && !isFinanceAdmin)
            return new CoordinatorCategoryDetailViewData(category, ShouldForbid: true, Teams: []);

        var coordinatorTeamIds = await GetEffectiveCoordinatorTeamIdsAsync(userId);
        if (!isFinanceAdmin && coordinatorTeamIds.Count == 0)
            return new CoordinatorCategoryDetailViewData(category, ShouldForbid: true, Teams: []);

        var teams = (await teamService.GetTeamsAsync()).Values
            .Where(t => t.IsActive)
            .ToList();
        return new CoordinatorCategoryDetailViewData(category, ShouldForbid: false, Teams: teams);
    }

    private static BudgetCategorySnapshot ToCategorySnapshot(
        BudgetCategory category,
        IReadOnlyDictionary<Guid, string> teamNamesById) =>
        new(
            category.Id,
            category.BudgetGroupId,
            category.Name,
            category.AllocatedAmount,
            category.ExpenditureType,
            category.TeamId,
            category.SortOrder,
            category.BudgetGroup is null
                ? null
                : new BudgetCategoryGroupSnapshot(
                    category.BudgetGroup.Id,
                    category.BudgetGroup.BudgetYearId,
                    category.BudgetGroup.Name,
                    category.BudgetGroup.IsRestricted,
                    category.BudgetGroup.IsTicketingGroup,
                    category.BudgetGroup.BudgetYear is null
                        ? null
                        : new BudgetCategoryYearSnapshot(
                            category.BudgetGroup.BudgetYear.Id,
                            category.BudgetGroup.BudgetYear.Year,
                            category.BudgetGroup.BudgetYear.Name,
                            category.BudgetGroup.BudgetYear.IsDeleted)),
            category.LineItems
                .Select(item => new BudgetCategoryLineItemSnapshot(
                    item.Id,
                    item.BudgetCategoryId,
                    item.Description,
                    item.Amount,
                    item.ResponsibleTeamId,
                    item.ResponsibleTeamId is { } rtid && teamNamesById.TryGetValue(rtid, out var name) ? name : null,
                    item.Notes,
                    item.ExpectedDate,
                    item.VatRate,
                    item.IsAutoGenerated,
                    item.IsCashflowOnly,
                    item.SortOrder))
                .ToList());

    public async Task<BudgetCategoryDetail> CreateCategoryAsync(
        Guid budgetGroupId, string name, decimal allocatedAmount,
        ExpenditureType expenditureType, Guid? teamId, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var category = await repository.CreateCategoryAsync(
            budgetGroupId, name, allocatedAmount, expenditureType, teamId, actorUserId, now);

        logger.LogInformation(
            "Created budget category '{Name}' in group {GroupId}", name, budgetGroupId);

        return ToCategoryDetail(category);
    }

    public async Task UpdateCategoryAsync(
        Guid categoryId, string name, decimal allocatedAmount,
        ExpenditureType expenditureType, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var ok = await repository.UpdateCategoryAsync(
            categoryId, name, allocatedAmount, expenditureType, actorUserId, now);
        if (!ok)
            throw new InvalidOperationException($"Budget category {categoryId} not found");
    }

    public async Task DeleteCategoryAsync(Guid categoryId, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var ok = await repository.DeleteCategoryAsync(categoryId, actorUserId, now);
        if (!ok)
            throw new InvalidOperationException($"Budget category {categoryId} not found");

        logger.LogInformation("Deleted budget category {CategoryId}", categoryId);
    }

    public async Task<BudgetLineItemSnapshot?> GetLineItemByIdAsync(Guid id)
    {
        var lineItem = await repository.GetLineItemByIdAsync(id);
        return lineItem is null ? null : ToLineItemSnapshot(lineItem);
    }

    private static BudgetLineItemSnapshot ToLineItemSnapshot(BudgetLineItem lineItem) =>
        new(
            lineItem.Id,
            lineItem.BudgetCategoryId,
            lineItem.Description,
            lineItem.Amount,
            lineItem.ResponsibleTeamId,
            lineItem.Notes,
            lineItem.ExpectedDate,
            lineItem.VatRate,
            lineItem.IsAutoGenerated,
            lineItem.IsCashflowOnly,
            lineItem.SortOrder);

    public async Task<BudgetLineItemSnapshot> CreateLineItemAsync(
        Guid budgetCategoryId, string description, decimal amount,
        Guid? responsibleTeamId, string? notes, LocalDate? expectedDate,
        int vatRate, Guid actorUserId)
    {
        ValidateVatRate(vatRate);

        var now = clock.GetCurrentInstant();

        var draft = new BudgetLineItemDraft(
            BudgetCategoryId: budgetCategoryId,
            Description: description,
            Amount: amount,
            ResponsibleTeamId: responsibleTeamId,
            Notes: notes,
            ExpectedDate: expectedDate,
            VatRate: vatRate);

        var lineItem = await repository.CreateLineItemAsync(draft, actorUserId, now);

        logger.LogInformation(
            "Created line item '{Description}' in category {CategoryId}",
            description, budgetCategoryId);

        return ToLineItemSnapshot(lineItem);
    }

    public async Task UpdateLineItemAsync(
        Guid lineItemId, string description, decimal amount,
        Guid? responsibleTeamId, string? notes, LocalDate? expectedDate,
        int vatRate, Guid actorUserId)
    {
        ValidateVatRate(vatRate);

        var now = clock.GetCurrentInstant();

        var update = new BudgetLineItemUpdate(
            LineItemId: lineItemId,
            Description: description,
            Amount: amount,
            ResponsibleTeamId: responsibleTeamId,
            Notes: notes,
            ExpectedDate: expectedDate,
            VatRate: vatRate);

        var ok = await repository.UpdateLineItemAsync(update, actorUserId, now);
        if (!ok)
            throw new InvalidOperationException($"Budget line item {lineItemId} not found");
    }

    private static void ValidateVatRate(int vatRate)
    {
        if (vatRate is < 0 or > 21)
            throw new ArgumentOutOfRangeException(nameof(vatRate), vatRate, "VAT rate must be between 0 and 21.");
    }

    public async Task DeleteLineItemAsync(Guid lineItemId, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var ok = await repository.DeleteLineItemAsync(lineItemId, actorUserId, now);
        if (!ok)
            throw new InvalidOperationException($"Budget line item {lineItemId} not found");

        logger.LogInformation("Deleted line item {LineItemId}", lineItemId);
    }

    public async Task UpdateTicketingProjectionAsync(
        Guid budgetGroupId, LocalDate? startDate, LocalDate? eventDate,
        int initialSalesCount, decimal dailySalesRate, decimal averageTicketPrice, int vatRate,
        decimal stripeFeePercent, decimal stripeFeeFixed, decimal ticketTailorFeePercent, Guid actorUserId)
    {
        var now = clock.GetCurrentInstant();

        var update = new TicketingProjectionUpdate(
            BudgetGroupId: budgetGroupId,
            StartDate: startDate,
            EventDate: eventDate,
            InitialSalesCount: initialSalesCount,
            DailySalesRate: dailySalesRate,
            AverageTicketPrice: averageTicketPrice,
            VatRate: vatRate,
            StripeFeePercent: stripeFeePercent,
            StripeFeeFixed: stripeFeeFixed,
            TicketTailorFeePercent: ticketTailorFeePercent);

        await repository.UpdateTicketingProjectionAsync(update, actorUserId, now);

        logger.LogInformation("Updated ticketing projection for group {GroupId}", budgetGroupId);
    }

    public async Task<IReadOnlyList<BudgetAuditLogSnapshot>> GetAuditLogAsync(Guid? budgetYearId)
    {
        var entries = await repository.GetAuditLogAsync(budgetYearId);
        return entries.Select(e => new BudgetAuditLogSnapshot(
            e.Id,
            e.BudgetYearId,
            e.EntityType,
            e.EntityId,
            e.FieldName,
            e.OldValue,
            e.NewValue,
            e.Description,
            e.ActorUserId,
            e.OccurredAt)).ToList();
    }

    public async Task<HashSet<Guid>> GetEffectiveCoordinatorTeamIdsAsync(Guid userId)
    {
        var ids = await teamService.GetEffectiveBudgetCoordinatorTeamIdsAsync(userId);
        return ids.ToHashSet();
    }

    public BudgetSummaryResult ComputeBudgetSummary(IReadOnlyList<BudgetGroupDetail> groups)
    {
        var groupsList = groups;

        var budgetLineItems = groupsList
            .SelectMany(g => g.Categories)
            .SelectMany(c => c.LineItems)
            .Where(li => !li.IsCashflowOnly)
            .ToList();

        var vatProjections = budgetLineItems
            .Where(li => li.VatRate > 0 && li.ExpectedDate.HasValue)
            .Select(li => new
            {
                VatAmount = Math.Abs(li.Amount) * li.VatRate / (100m + li.VatRate),
                IsExpense = li.Amount > 0 // Income generates VAT liability (expense).
            })
            .ToList();

        var income = budgetLineItems.Where(li => li.Amount > 0).Sum(li => li.Amount);
        var expenses = budgetLineItems.Where(li => li.Amount < 0).Sum(li => li.Amount);
        var vatExpenses = vatProjections.Where(v => v.IsExpense).Sum(v => v.VatAmount);
        var vatCredits = vatProjections.Where(v => !v.IsExpense).Sum(v => v.VatAmount);

        var totalIncome = income + vatCredits;
        var totalExpenses = expenses - vatExpenses;
        var netBalance = totalIncome + totalExpenses;

        var incomeCategories = groupsList
            .SelectMany(g => g.Categories)
            .Select(c => new { c.Name, Total = c.LineItems.Where(li => li.Amount > 0 && !li.IsCashflowOnly).Sum(li => li.Amount) })
            .Where(c => c.Total > 0)
            .OrderByDescending(c => c.Total)
            .ToList();

        if (vatCredits > 0)
            incomeCategories.Add(new { Name = "VAT Credits", Total = vatCredits });

        var totalIncomeForSlices = incomeCategories.Sum(c => c.Total);
        var incomeSlices = incomeCategories
            .Select(c => new BudgetSliceResult
            {
                Name = c.Name,
                Amount = c.Total,
                Percentage = totalIncomeForSlices > 0 ? c.Total / totalIncomeForSlices * 100 : 0
            })
            .ToList();

        var expenseCategories = groupsList
            .SelectMany(g => g.Categories)
            .Select(c => new { c.Name, Total = Math.Abs(c.LineItems.Where(li => li.Amount < 0 && !li.IsCashflowOnly).Sum(li => li.Amount)) })
            .Where(c => c.Total > 0)
            .OrderByDescending(c => c.Total)
            .ToList();

        if (vatExpenses > 0)
            expenseCategories.Add(new { Name = "VAT Liability", Total = vatExpenses });

        var profit = income + vatCredits - (Math.Abs(expenses) + vatExpenses);
        if (profit > 0)
        {
            expenseCategories.Add(new { Name = "Cash Reserves (90%)", Total = profit * 0.9m });
            expenseCategories.Add(new { Name = "Spanish Taxes (10%)", Total = profit * 0.1m });
        }

        var totalExpenseForSlices = expenseCategories.Sum(c => c.Total);
        var expenseSlices = expenseCategories
            .Select(c => new BudgetSliceResult
            {
                Name = c.Name,
                Amount = c.Total,
                Percentage = totalExpenseForSlices > 0 ? c.Total / totalExpenseForSlices * 100 : 0
            })
            .ToList();

        return new BudgetSummaryResult
        {
            TotalIncome = totalIncome,
            TotalExpenses = totalExpenses,
            NetBalance = netBalance,
            IncomeSlices = incomeSlices,
            ExpenseSlices = expenseSlices
        };
    }

    public BudgetSummaryResult ComputeBudgetSummaryWithBuffers(IReadOnlyList<BudgetGroupDetail> groups)
    {
        var groupList = groups;
        var summary = ComputeBudgetSummary(groupList);

        // Per-group buffer: allocated minus line-item total (negative = expense, positive = income).
        var groupBuffers = groupList
            .Where(g => !g.IsTicketingGroup)
            .Select(g => new
            {
                Name = $"{g.Name} Buffer",
                Raw = g.Categories.Sum(c =>
                    c.AllocatedAmount - c.LineItems.Where(li => !li.IsCashflowOnly).Sum(li => li.Amount))
            })
            .Where(b => b.Raw != 0)
            .ToList();

        var allExpenseEntries = summary.ExpenseSlices
            .Select(s => new { s.Name, s.Amount })
            .Concat(groupBuffers.Where(b => b.Raw < 0).Select(b => new { b.Name, Amount = Math.Abs(b.Raw) }))
            .ToList();
        var totalExpense = allExpenseEntries.Sum(s => s.Amount);

        var allIncomeEntries = summary.IncomeSlices
            .Select(s => new { s.Name, s.Amount })
            .Concat(groupBuffers.Where(b => b.Raw > 0).Select(b => new { b.Name, Amount = b.Raw }))
            .ToList();
        var totalIncome = allIncomeEntries.Sum(s => s.Amount);

        return new BudgetSummaryResult
        {
            TotalIncome = summary.TotalIncome,
            TotalExpenses = summary.TotalExpenses,
            NetBalance = summary.NetBalance,
            IncomeSlices = allIncomeEntries
                .Select(s => new BudgetSliceResult
                {
                    Name = s.Name,
                    Amount = s.Amount,
                    Percentage = totalIncome > 0 ? s.Amount / totalIncome * 100 : 0
                })
                .ToList(),
            ExpenseSlices = allExpenseEntries
                .Select(s => new BudgetSliceResult
                {
                    Name = s.Name,
                    Amount = s.Amount,
                    Percentage = totalExpense > 0 ? s.Amount / totalExpense * 100 : 0
                })
                .ToList()
        };
    }

    public IReadOnlyList<VatCashFlowEntry> ComputeVatCashFlowEntries(IReadOnlyList<BudgetGroupDetail> groups)
    {
        return groups
            .SelectMany(g => g.Categories)
            .SelectMany(c => c.LineItems)
            .Where(li => li.VatRate > 0 && li.ExpectedDate.HasValue)
            .Select(li =>
            {
                var vatAmount = Math.Abs(li.Amount) * li.VatRate / (100m + li.VatRate);
                // Income → VAT liability (expense); expense → VAT credit (income).
                var cashFlowAmount = li.Amount > 0 ? -vatAmount : vatAmount;
                var categoryName = li.Amount > 0 ? "VAT Liability" : "VAT Credits";
                return new VatCashFlowEntry
                {
                    CategoryName = categoryName,
                    Amount = cashFlowAmount,
                    SettlementDate = ComputeVatSettlementDate(li.ExpectedDate!.Value)
                };
            })
            .ToList();
    }

    private static LocalDate ComputeVatSettlementDate(LocalDate expectedDate)
    {
        var quarterEnd = expectedDate.Month switch
        {
            >= 1 and <= 3 => new LocalDate(expectedDate.Year, 3, 31),
            >= 4 and <= 6 => new LocalDate(expectedDate.Year, 6, 30),
            >= 7 and <= 9 => new LocalDate(expectedDate.Year, 9, 30),
            _ => new LocalDate(expectedDate.Year, 12, 31)
        };

        return quarterEnd.PlusDays(45);
    }

    // Projected-week materialization lives in repo to avoid projected-items-lag-one-sync.
    public async Task<int> SyncTicketingActualsAsync(
        Guid budgetYearId,
        IReadOnlyList<TicketingWeeklyActuals> weeklyActuals,
        CancellationToken ct = default)
    {
        var now = clock.GetCurrentInstant();
        var today = now.InUtc().Date;

        var actualsInputs = weeklyActuals
            .Select(w => new TicketingWeeklyActualsInput(
                WeekLabel: w.WeekLabel,
                Monday: w.Monday,
                TicketCount: w.TicketCount,
                Revenue: w.Revenue,
                StripeFees: w.StripeFees,
                TicketTailorFees: w.TicketTailorFees))
            .ToList();

        var changed = await repository.SyncTicketingActualsAsync(
            budgetYearId, actualsInputs, today, now, ct);

        logger.LogInformation(
            "Ticketing budget sync: {Created} line items created/updated for {Weeks} actual weeks + projections",
            changed, weeklyActuals.Count);

        return changed;
    }

    public async Task<int> RefreshTicketingProjectionsAsync(Guid budgetYearId, CancellationToken ct = default)
    {
        var now = clock.GetCurrentInstant();
        var today = now.InUtc().Date;

        var created = await repository.RefreshTicketingProjectionsAsync(budgetYearId, today, now, ct);

        logger.LogInformation("Ticketing projections refreshed: {Count} line items", created);
        return created;
    }

    public async Task<IReadOnlyList<TicketingWeekProjection>> GetTicketingProjectionEntriesAsync(
        Guid budgetGroupId, CancellationToken ct = default)
    {
        var group = await repository.GetGroupByIdAsync(budgetGroupId, ct);
        if (group is null || !group.IsTicketingGroup)
            return [];

        var projection = await repository.GetTicketingProjectionAsync(budgetGroupId, ct);
        if (projection is null)
            return [];

        if (projection.StartDate is null
            || projection.EventDate is null
            || projection.AverageTicketPrice == 0)
        {
            return [];
        }

        var today = clock.GetCurrentInstant().InUtc().Date;
        var currentWeekMonday = GetTicketingIsoMonday(today);

        var projectionStart = currentWeekMonday > projection.StartDate.Value
            ? currentWeekMonday
            : GetTicketingIsoMonday(projection.StartDate.Value);
        var eventDate = projection.EventDate.Value;

        if (projectionStart >= eventDate)
            return [];

        var dailyRate = projection.DailySalesRate;
        var initialBurst = projection.InitialSalesCount;
        var isFirstWeek = true;

        var projections = new List<TicketingWeekProjection>();
        var weekStart = projectionStart;

        while (weekStart < eventDate)
        {
            var weekEnd = weekStart.PlusDays(6);
            if (weekEnd > eventDate) weekEnd = eventDate;

            var daysInWeek = Period.Between(weekStart, weekEnd.PlusDays(1), PeriodUnits.Days).Days;
            var weekTickets = (int)Math.Round(dailyRate * daysInWeek);
            if (isFirstWeek && projectionStart <= projection.StartDate.Value)
            {
                weekTickets += initialBurst;
                isFirstWeek = false;
            }
            else
            {
                isFirstWeek = false;
            }
            if (weekTickets <= 0) weekTickets = 1;

            var weekRevenue = weekTickets * projection.AverageTicketPrice;
            var stripeFees = weekRevenue * projection.StripeFeePercent / 100m +
                             weekTickets * projection.StripeFeeFixed;
            var ttFees = weekRevenue * projection.TicketTailorFeePercent / 100m;

            projections.Add(new TicketingWeekProjection
            {
                WeekLabel = FormatTicketingWeekLabel(weekStart, weekEnd),
                WeekStart = weekStart,
                WeekEnd = weekEnd,
                ProjectedTickets = weekTickets,
                ProjectedRevenue = Math.Round(weekRevenue, 2),
                ProjectedStripeFees = Math.Round(stripeFees, 2),
                ProjectedTtFees = Math.Round(ttFees, 2)
            });

            weekStart = weekEnd.PlusDays(1);
            weekStart = GetTicketingIsoMonday(weekStart);
            if (weekStart <= weekEnd) weekStart = weekEnd.PlusDays(1);
        }

        return projections;
    }

    public int GetActualTicketsSold(BudgetGroupDetail ticketingGroup)
    {
        var revenueCategory = ticketingGroup.Categories
            .FirstOrDefault(c => string.Equals(c.Name, "Ticket Revenue", StringComparison.Ordinal));

        if (revenueCategory is null) return 0;

        return SumActualTicketsSold(revenueCategory.LineItems
            .Select(item => (item.IsAutoGenerated, item.Description, item.Notes)));
    }

    // Actual-tickets sum from auto-generated revenue notes "N tickets" (projected use "~N").
    private static int SumActualTicketsSold(IEnumerable<(bool IsAutoGenerated, string Description, string? Notes)> items)
    {
        var total = 0;
        foreach (var item in items)
        {
            if (!item.IsAutoGenerated) continue;
            if (item.Description.StartsWith("Projected: ", StringComparison.Ordinal)) continue;
            if (string.IsNullOrEmpty(item.Notes)) continue;

            var notes = item.Notes.TrimStart('~');
            var spaceIdx = notes.IndexOf(' ', StringComparison.Ordinal);
            if (spaceIdx > 0 && int.TryParse(
                notes.AsSpan(0, spaceIdx),
                NumberStyles.Integer,
                CultureInfo.InvariantCulture,
                out var count))
            {
                total += count;
            }
        }

        return total;
    }

    private static LocalDate GetTicketingIsoMonday(LocalDate date)
    {
        // NodaTime IsoDayOfWeek: Monday=1, Sunday=7.
        var dayOfWeek = (int)date.DayOfWeek;
        return date.PlusDays(-(dayOfWeek - 1));
    }

    private static string FormatTicketingWeekLabel(LocalDate monday, LocalDate sunday)
    {
        return $"{monday.ToString("MMM d", null)}–{sunday.ToString("MMM d", null)}";
    }

    public async Task<IReadOnlyList<UserDataSlice>> ContributeForUserAsync(Guid userId, CancellationToken ct)
    {
        // Chain-follow merge tombstones — GDPR export must include merged-source audit rows.
        var sourceIds = await userService.GetMergedSourceIdsAsync(userId, ct);
        IReadOnlyList<BudgetAuditLog> entries;
        if (sourceIds.Count == 0)
        {
            entries = await repository.GetAuditLogEntriesForUserAsync(userId, ct);
        }
        else
        {
            var allIds = new List<Guid>(sourceIds.Count + 1);
            allIds.AddRange(sourceIds);
            allIds.Add(userId);
            entries = await repository.GetAuditLogEntriesForUserIdsAsync(allIds, ct);
        }

        var shaped = entries.Select(bal => new
        {
            bal.EntityType,
            bal.FieldName,
            bal.Description,
            OccurredAt = bal.OccurredAt.ToInvariantInstantString()
        }).ToList();

        return [new UserDataSlice(GdprExportSections.BudgetAuditLog, shaped)];
    }
}
